# Описание командной утилиты по работе с базой данных:
# https://github.com/launchbadge/sqlx/tree/master/sqlx-cli

.SILENT:
.PHONY:

START_POSTGRES:
	docker-compose up

START_PG_CLI:
	pgcli -U pg -d cources -h 127.0.0.1